### ISSUE TITLE
Create a proper GitHub fork

### ISSUE THREAD

**Issue by plata** [EinoHR/create-ublue-image#14]
Currently, the created repos set the upstream but are not recognized as forks of startingpoint. This prevents from syncing via GitHub directly (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

As adviced in https://ublue.it/making-your-own/
> Ensure you are forking the repository and NOT choosing "Use this template". The project moves quickly and it's important for you to get updates!

**Comment by EinoHR** [comment]
This is intentional behaviour. A Github user can only have one fork of a repository. When creating this tool, I already had a fork of ublue-os/base, which also counts. If somebody was transitioning over from their fork of ublue-os/base to a new image based on ublue-os/startingpoint, the tool would error out.

Also, as I've observed, when people make a fork of startingpoint they might accidentally PR their personal changes into it, which shouldn't be easy to do accidentally when using a repo created with this tool.

As also adviced in https://ublue.it/making-your-own/
> In order to update changes from the upstream repository, run:
> ```
> git fetch upstream
> git merge upstream/main -m "chore: merging upstream changes"
> ```
